name: Commnader_Wars
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.2.2'
  
jobs:
  install:
    name: All
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            COMPILER_VERSION: 'win64_mingw'
            target: 'desktop'
            qtPath: 'mingw_64'
            installerCommands1: ''
            installerCommands2: ''
            cmakeArgs: '-GMinGW Makefiles'
          - os: ubuntu-latest
            COMPILER_VERSION: ''
            target: 'desktop'
            qtPath: ''
            installerCommands1: 'sudo apt-get update'
            cmakeArgs: ''
          - os: macos-latest
            COMPILER_VERSION: 'clang_64'
            qtPath: 'clang_64'
            target: 'desktop'
            installerCommands1: ''
            installerCommands2: ''
            cmakeArgs: ''
          #- os: ubuntu-latest
          #  COMPILER_VERSION: 'android_armv7'
          #  target: 'android'
        
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
          
    - name: Install OS Dependencies 1
      run: ${{matrix.installerCommands1}}
    
    - name: Install OS Dependencies 2
      run: ${{matrix.installerCommands2}}
      
    - name: Configure CMake
      run: |
        cmake \
        -B '${{github.workspace}}/build' \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install' \
        -DCMAKE_PREFIX_PATH="${{github.workspace}}/qt/Qt/${{matrix.qtPath}}/lib/cmake/" \
        -DQt6_DIR=${{github.workspace}}/qt/Qt/${{matrix.qtPath}}/lib/cmake/Qt6/ \
        ${{cmakeArgs}}
    
    - name: Build
      working-directory: '${{github.workspace}}/build'
      run: cmake --build '${{github.workspace}}/build' --config $BUILD_TYPE --target install -j16
