name: CMake
on: [push]
env:
  BUILD_TYPE: RelWithDebInfo
  compiler: gcc
jobs:
  install:
    name: All
    runs-on: windows-latest
    steps:
    - uses: jurplel/install-qt-action@v2
      with:
          version: '5.15.2'
          target: 'desktop'
          arch: 'win64_mingw81'
          dir: '${{ github.workspace }}/qt/'
          cached: 'false'
          setup-python: 'true'
          tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Translate
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -DCMAKE_PREFIX_PATH=${{ github.workspace }}/qt/ -DCMAKE_CXX_COMPILER=g++-10 --target Commander_Wars_translations
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -DCMAKE_PREFIX_PATH=${{ github.workspace }}/qt/ -DCMAKE_CXX_COMPILER=g++-10 --target install
