name: CMake
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.2.1'
  COMPILER_VERSION: 'mingw-w64-x86_64'
  # 'win64_msvc2019_64'
  
jobs:
  install:
    name: All
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
          install: mingw-w64-x86_64-toolchain
          msystem: mingw64
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2    
      with:
          version: ${{env.QT_Version}}
          target: 'desktop'
          arch: ${{env.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{ github.workspace }}/qt/'
          install-deps: "true"
          
    - name: Configure CMake
      env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}          
      run: cmake -B '${{github.workspace}}'/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}    
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build '${{github.workspace}}'/build --config $BUILD_TYPE --target install
