name: Commnader_Wars
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.2.1'
  
jobs:
  install:
    name: All
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] #  , macos-latest
        include:
          - os: windows-latest
            COMPILER_VERSION: 'win64_msvc2019_64'
            # 'win64_mingw81'
            target: 'desktop'
            installerCommands: ''
          - os: ubuntu-latest
            COMPILER_VERSION: ''
            target: 'desktop'
            installerCommands: 'apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio'
          #- os: macos-latest
          #  COMPILER_VERSION: ''
          #  target: 'ios'
          #- os: windows-latest
          #  COMPILER_VERSION: 'android_armv7'
          #  target: 'android'
        
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Install OS Dependencies
      run: ${{matrix.installerCommands}}
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2    
      with:      
          aqtversion: '==2.0.2'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
          
    - name: Configure CMake
      env:
          CMAKE_PREFIX_PATH: '${{env.Qt6_Dir}}'
      run: cmake -B '${{github.workspace}}/build' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install'
    
    - name: Build
      working-directory: '${{github.workspace}}/build'
      run: cmake --build '${{github.workspace}}/build' --config $BUILD_TYPE --target install -j16
